---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tee.cloud.google.com
  resources:
  - confidentialspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tee.cloud.google.com
  resources:
  - confidentialspaces/finalizers
  verbs:
  - update
- apiGroups:
  - tee.cloud.google.com
  resources:
  - confidentialspaces/status
  verbs:
  - get
  - patch
  - update
