apiVersion: tee.cloud.google.com/v1alpha1
kind: ConfidentialSpace
metadata:
  labels:
    app.kubernetes.io/name: confidential-space-operator
    app.kubernetes.io/managed-by: kustomize
  name: confidentialspace-sample
spec:
  # TODO(user): Add fields here
